[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
capital-d = "standard-unilateral-serifed"
capital-q = "straight"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
a = "single-storey-serifless"
f = "serifless"
i = "tailed-serifed"
j = "serifed"
l = "hooky"
m = "normal"
q = "straight"
t = "standard"
y = "straight"
zero = "slashed"
one = "base"
three = "flat-top"
tilde = "low"
asterisk = "penta-low"
brace = "curly"
at = "threefold"
dollar = "open-cap"
percent = "dots"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"
